### ISSUE TITLE
Right hemisphere delete

### ISSUE THREAD

**Issue by francopestilli** [brain-life/ui-tractview#11]
There seems to be an issue with the current version deployed on brainlife.io when unselecting all tracts only the left-hemisphere tracts are removed from the visualization. All right hemisphere tracts stay. @soichih @stevengeeky

**Comment by soichih** [comment]
This is a duplicate of issue #10 Steven will fix this.

**Comment by soichih** [comment]
@stevengeeky Fixed this.
