### ISSUE TITLE
Allow users to upload overlay .nii.gz

### ISSUE THREAD

**Issue by soichih** [brain-life/ui-tractview#14]
I've been thinking about how to allow user to load *any* .nii.gz via Brainlife, and I believe we should allow users to load .nii.gz via the tractview UI - by placing a "upload" button on the UI itself and allowing user to select .nii.gz stored locally on user's machine.

For Brainlife, the use case might be following.

1) User download some scalar nifti image (from recon, dtiinit, noddi output) from Brainlife.
2) User launches tractview from wmc output via Brainlife.
3) Once tractview starts up (and loads the wmc tracts), user then click "Upload overlay image" button.
4) User select the nifti image stored locally, and tractview would load it to the tractview

I think we should pursuit mechanism to pre-load nifti images as *layer* like we are doing now, but by allowing user to load locally stored nifti image, it makes it much more flexible and allows user to explore their data including data from Brainlife

**Comment by stevengeeky** [comment]
I think I might just do this to make dev testing way easier
